# Generated by Django 6.1.1 on 2026-09-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_multiple_floors', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_quick_issue', models.BooleanField(default=False, help_text='Shown as a one-tap chip on the create-ticket form.')),
                ('default_department', models.ForeignKey(blank=True, help_text='Department a ticket auto-routes to when this issue is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='tickets.office')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_dept_assignment', 'Pending Department Assignment'), ('pending_technician_assignment', 'Pending Technician Assignment'), ('pending_technician_assessment', 'Pending Technician Assessment'), ('pending_dept_poc_review', 'Pending Department POC Review'), ('resolved_full', 'Resolved (Full)'), ('resolved_partial', 'Resolved (Partial)'), ('closed', 'Closed')], default='pending_dept_assignment', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.department')),
                ('floors', models.ManyToManyField(blank=True, related_name='tickets', to='tickets.floor')),
                ('issues', models.ManyToManyField(related_name='tickets', to='tickets.issue')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.office')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('client', 'Client'), ('department_poc', 'Department POC'), ('technician', 'Technician')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='tickets.department')),
            ],
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text="Used when there's no actor, e.g. 'System'.", max_length=100)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('auto_assigned', 'Auto Assigned'), ('assigned_technician', 'Assigned Technician'), ('department_changed', 'Department Changed'), ('status_changed', 'Status Changed'), ('comment', 'Comment'), ('resolved', 'Resolved')], max_length=30)),
                ('from_value', models.CharField(blank=True, max_length=150)),
                ('to_value', models.CharField(blank=True, max_length=150)),
                ('comment_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='tickets.userprofile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='tickets.userprofile'),
        ),
    ]
